DROP SCHEMA SEMIPROJECT;
CREATE SCHEMA SEMIPROJECT;
USE SEMIPROJECT;



------------------------------------------------
--------------- MEMBER 관련 테이블 ----------------
------------------------------------------------

CREATE TABLE MEMBER (
    mNO 	 INT  PRIMARY KEY AUTO_INCREMENT,
    ID 		 VARCHAR(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    ROLE 	 VARCHAR(10) DEFAULT 'ROLE_USER',
    NAME 	 VARCHAR(15) NOT NULL,
    PHONE 	 VARCHAR(13),
    EMAIL 	 VARCHAR(100),
    ADDRESS  VARCHAR(100),
    FAVORITEGENRE 	 VARCHAR(100),
    KAKAOTOKEN	VARCHAR(1000),
    STATUS 	 VARCHAR(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    ENROLL_DATE DATETIME  DEFAULT CURRENT_TIMESTAMP,
    MODIFY_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO MEMBER (
    mNO, ID, PASSWORD,  ROLE, NAME, 
    PHONE, EMAIL, ADDRESS, FAVORITEGENRE,  KAKAOTOKEN, 
    STATUS,  ENROLL_DATE, MODIFY_DATE
) VALUES(
    0, 'admin', '1234', 'ROLE_ADMIN', '관리자', 
    '010-1234-4341', 'admin@test.com', '서울시 강남구 역삼동', DEFAULT,DEFAULT, DEFAULT,
    DEFAULT, DEFAULT
);
INSERT INTO MEMBER (
    mNO, ID, PASSWORD,  ROLE, NAME, 
    PHONE, EMAIL, ADDRESS, FAVORITEGENRE,  KAKAOTOKEN, 
    STATUS,  ENROLL_DATE, MODIFY_DATE
) VALUES(
    0, 'test1', '1234', DEFAULT, '실험멤버1', 
    '010-1234-4341', 'member1@test.com', '서울시 종로', DEFAULT,DEFAULT, DEFAULT,
    DEFAULT, DEFAULT
);
INSERT INTO MEMBER (
    mNO, ID, PASSWORD,  ROLE, NAME, 
    PHONE, EMAIL, ADDRESS, FAVORITEGENRE,  KAKAOTOKEN, 
    STATUS,  ENROLL_DATE, MODIFY_DATE
) VALUES(
    0, 'test2', '1234', DEFAULT, '실험멤버2', 
    '010-1234-4341', 'member2@test.com', '서울시 신촌', DEFAULT,DEFAULT, DEFAULT,
    DEFAULT, DEFAULT
);

SELECT * FROM MEMBER;





------------------------------------------------
--------------- PRFBOARD 공연게시판 테이블 ----------------
------------------------------------------------

CREATE TABLE PRFBOARD (	
    bNO INT AUTO_INCREMENT,
    mNO INT, 
    PNAME VARCHAR(100), 
	TITLE VARCHAR(1000), 
	CONTENT VARCHAR(2000), 
    RATINGS INT, 
    ATTACHCOUNT INT DEFAULT 0, 
	READCOUNT INT DEFAULT 0, 
    STATUS VARCHAR(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    CREATE_DATE DATETIME  DEFAULT CURRENT_TIMESTAMP, 
    MODIFY_DATE DATETIME  DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PRFBOARD_NO PRIMARY KEY(bNO),
    CONSTRAINT FK_PRFBOARD_WRITER FOREIGN KEY(mNO) REFERENCES MEMBER(mNO) ON DELETE SET NULL
);

INSERT INTO PRFBOARD (bNO, mNO, PNAME, TITLE, CONTENT, RATINGS) VALUES(0,2,'몬테크리스토','정말 추천하고 응원하는 뮤지컬 :)','뮤지컬 몬테크리스토를 보기 위해 티켓팅날 예매를 하고 엄마와 함께 공연을 보러 갔었습니다.많은 배우님들이 연기를 하시는데 김성철 배우님의 몬테크리스토 백작이 보고싶어서 이 날로 예매했었어요.뮤지컬 몬테크리스토는 처음 보는 공연', 5);
INSERT INTO PRFBOARD (bNO, mNO, PNAME, TITLE, CONTENT, RATINGS) VALUES(0,1,'몬테크리스토', '퀄리티가 괜찮았음', '초등생 이하 아이들이 보기에 괜찮은 것 같아요.배우들의 가창력, 춤도 괜찮았고 무대세트도 퀄리티가 좋았어요.', 3);
INSERT INTO PRFBOARD (bNO, mNO, PNAME, TITLE, CONTENT, RATINGS) VALUES(0,2,'레미제라블', '정말 소름돋는 최고의무대.', '홍자 요미 카이까지 정말최고의무대였어요 공연퀄이 정말 멋졌어요 나날이달라지네요', 4);
INSERT INTO PRFBOARD (bNO, mNO, PNAME, TITLE, CONTENT, RATINGS) VALUES(0,3,'레미제라블','끝내줬습니다', '오랜만에 아이랑 뮤지컬본거라 혹시 유치하지않을까 싶기도했지만 웬걸..저도 너무 재밌고 신기했습니다 다른편 나오면 꼭 다시 보려합니다ㅎㅎ', 5);

SELECT * FROM PRFBOARD;


CREATE TABLE PRFBOARD_ATTACH_FILE (
	fNO INT AUTO_INCREMENT, 
    bNO INT,
    ORIGINAL_FILENAME VARCHAR(200), 
	RENAMED_FILENAME VARCHAR(200), 
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP, 
    CONSTRAINT PK_PRFBOARD_ATTACH_FILE PRIMARY KEY(fNO),
    CONSTRAINT FK_PRFBOARD_BO FOREIGN KEY(bNO) REFERENCES PRFBOARD(bNO) ON DELETE CASCADE
);

CREATE TABLE PRFREPLY(
  rNO INT PRIMARY KEY AUTO_INCREMENT,
  bNO INT,
  mNO INT,
  CONTENT VARCHAR(1000),
  STATUS VARCHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (bNO) REFERENCES PRFBOARD(bNO) ON DELETE CASCADE,
  FOREIGN KEY (mNO) REFERENCES MEMBER(mNO) ON DELETE SET NULL 
);

INSERT INTO PRFREPLY (rNO, bNO, mNO, CONTENT) VALUES(0, 1, 1, '공감합니다');
INSERT INTO PRFREPLY (rNO, bNO, mNO, CONTENT) VALUES(0, 1, 2, '좋아요');
INSERT INTO PRFREPLY (rNO, bNO, mNO, CONTENT) VALUES(0, 2, 3, '저도 봤습니다');
INSERT INTO PRFREPLY (rNO, bNO, mNO, CONTENT) VALUES(0, 3, 2, '아직 관람 안 하셨다면 꼭 보시길 권합니다. 진짜로...');

SELECT * FROM PRFREPLY;


------------------------------------------------
--------------- TOURBOARD 관광게시판 테이블 ----------------
------------------------------------------------

CREATE TABLE TOURBOARD (	
    bNO INT AUTO_INCREMENT,
    mNO INT, 
    T_TITLE VARCHAR(100), 
	TITLE VARCHAR(1000), 
	CONTENT VARCHAR(2000), 
    RATINGS INT, 
    ATTACHCOUNT INT DEFAULT 0, 
	READCOUNT INT DEFAULT 0, 
    STATUS VARCHAR(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    CREATE_DATE DATETIME  DEFAULT CURRENT_TIMESTAMP, 
    MODIFY_DATE DATETIME  DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TOURBOARD_NO PRIMARY KEY(bNO),
    CONSTRAINT FK_TOURBOARD_WRITER FOREIGN KEY(mNO) REFERENCES MEMBER(mNO) ON DELETE SET NULL
);

CREATE TABLE TOURBOARD_ATTACH_FILE (
	fNO INT AUTO_INCREMENT, 
    bNO INT,
    ORIGINAL_FILENAME VARCHAR(200), 
	RENAMED_FILENAME VARCHAR(200), 
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP, 
    CONSTRAINT PK_TOURBOARD_ATTACH_FILE PRIMARY KEY(fNO),
    CONSTRAINT FK_TOURBOARD_BO FOREIGN KEY(bNO) REFERENCES TOURBOARD(bNO) ON DELETE CASCADE
);

CREATE TABLE TOURREPLY(
  rNO INT PRIMARY KEY AUTO_INCREMENT,
  bNO INT,
  mNO INT,
  CONTENT VARCHAR(1000),
  STATUS VARCHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (bNO) REFERENCES TOURBOARD(bNO) ON DELETE CASCADE,
  FOREIGN KEY (mNO) REFERENCES MEMBER(mNO) ON DELETE SET NULL 
);













