DROP SCHEMA SEMIPROJECT;
CREATE SCHEMA SEMIPROJECT;
USE SEMIPROJECT;



------------------------------------------------
--------------- MEMBER 관련 테이블 ----------------
------------------------------------------------

CREATE TABLE MEMBER (
    mNO 	 INT  PRIMARY KEY AUTO_INCREMENT,
    ID 		 VARCHAR(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    ROLE 	 VARCHAR(10) DEFAULT 'ROLE_USER',
    NAME 	 VARCHAR(15) NOT NULL,
    PHONE 	 VARCHAR(13),
    EMAIL 	 VARCHAR(100),
    ADDRESS  VARCHAR(100),
    FAVORITEGENRE 	 VARCHAR(100),
    KAKAOTOKEN	VARCHAR(1000),
    STATUS 	 VARCHAR(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    ENROLL_DATE DATETIME  DEFAULT CURRENT_TIMESTAMP,
    MODIFY_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO MEMBER (
    mNO, ID, PASSWORD,  ROLE, NAME, 
    PHONE, EMAIL, ADDRESS, FAVORITEGENRE,  KAKAOTOKEN, 
    STATUS,  ENROLL_DATE, MODIFY_DATE
) VALUES(
    0, 'admin', '1234', 'ROLE_ADMIN', '관리자', 
    '010-1234-4341', 'admin@test.com', '서울시 강남구 역삼동', DEFAULT,DEFAULT, DEFAULT,
    DEFAULT, DEFAULT
);
INSERT INTO MEMBER (
    mNO, ID, PASSWORD,  ROLE, NAME, 
    PHONE, EMAIL, ADDRESS, FAVORITEGENRE,  KAKAOTOKEN, 
    STATUS,  ENROLL_DATE, MODIFY_DATE
) VALUES(
    0, 'test1', '1234', DEFAULT, '실험멤버1', 
    '010-1234-4341', 'member1@test.com', '서울시 종로', DEFAULT,DEFAULT, DEFAULT,
    DEFAULT, DEFAULT
);
INSERT INTO MEMBER (
    mNO, ID, PASSWORD,  ROLE, NAME, 
    PHONE, EMAIL, ADDRESS, FAVORITEGENRE,  KAKAOTOKEN, 
    STATUS,  ENROLL_DATE, MODIFY_DATE
) VALUES(
    0, 'test2', '1234', DEFAULT, '실험멤버2', 
    '010-1234-4341', 'member2@test.com', '서울시 신촌', DEFAULT,DEFAULT, DEFAULT,
    DEFAULT, DEFAULT
);

SELECT * FROM MEMBER;





------------------------------------------------
--------------- PRFBOARD 공연게시판 테이블 ----------------
------------------------------------------------

CREATE TABLE PRFBOARD (	
    bNO INT AUTO_INCREMENT,
    mNO INT, 
    PNAME VARCHAR(100), 
	TITLE VARCHAR(1000), 
	CONTENT VARCHAR(2000), 
    RATINGS INT, 
    ATTACHCOUNT INT DEFAULT 0, 
	READCOUNT INT DEFAULT 0, 
    STATUS VARCHAR(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    CREATE_DATE DATETIME  DEFAULT CURRENT_TIMESTAMP, 
    MODIFY_DATE DATETIME  DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PRFBOARD_NO PRIMARY KEY(bNO),
    CONSTRAINT FK_BOARD_WRITER FOREIGN KEY(mNO) REFERENCES MEMBER(mNO) ON DELETE SET NULL
);

INSERT INTO PRFBOARD (bNO, mNO, PNAME, TITLE, CONTENT, RATINGS) VALUES(0,2,'몬테크리스토','정말 추천하고 응원하는 뮤지컬 :)','뮤지컬 몬테크리스토를 보기 위해 티켓팅날 예매를 하고 엄마와 함께 공연을 보러 갔었습니다.많은 배우님들이 연기를 하시는데 김성철 배우님의 몬테크리스토 백작이 보고싶어서 이 날로 예매했었어요.뮤지컬 몬테크리스토는 처음 보는 공연', 5);


SELECT * FROM PRFBOARD;


CREATE TABLE PRFBOARD_ATTACH_FILE (
	fNO INT AUTO_INCREMENT, 
    bNO INT,
    ORIGINAL_FILENAME VARCHAR(200), 
	RENAMED_FILENAME VARCHAR(200), 
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP, 
    CONSTRAINT PK_PRFBOARD_ATTACH_FILE PRIMARY KEY(fNO),
    CONSTRAINT FK_PRFBOARD_BO FOREIGN KEY(bNO) REFERENCES PRFBOARD(bNO) ON DELETE CASCADE
);

CREATE TABLE PRFREPLY(
  rNO INT PRIMARY KEY AUTO_INCREMENT,
  bNO INT,
  mNO INT,
  CONTENT VARCHAR(1000),
  STATUS VARCHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFY_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (bNO) REFERENCES PRFBOARD(bNO) ON DELETE CASCADE,
  FOREIGN KEY (mNO) REFERENCES MEMBER(mNO) ON DELETE SET NULL 
);

INSERT INTO PRFREPLY (rNO, bNO, mNO, CONTENT) VALUES(0, 1, 2, '공감합니다');

SELECT * FROM PRFREPLY;
















